"use client";

import {useEffect, useState} from "react";
import {Catalog, CatalogStatus, getCatalogStatus, publishCatalog, validateCatalog} from "@/lib/api";

const blankCatalog: Catalog = {catalog_version: "1", metrics: {}, dimensions: {}, join_contracts: [], column_policies: {}, privacy: {privacy_unit: "", minimum_group_size: 5}};
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

const labels = {en: {title: "Semantic Catalog", schema: "Schema browser", metrics: "Metrics", dimensions: "Dimensions", joins: "Join Contracts", privacy: "Privacy", validate: "Validate", draft: "Save Draft", publish: "Publish"}, ar: {title: "الكتالوج الدلالي", schema: "متصفح المخطط", metrics: "المقاييس", dimensions: "الأبعاد", joins: "عقود الربط", privacy: "الخصوصية", validate: "تحقق", draft: "حفظ المسودة", publish: "نشر"}};

export function CatalogConfigurator({profileId, locale, onReady}: {profileId: string; locale: "en" | "ar"; onReady: () => void}) {
  const [status, setStatus] = useState<CatalogStatus | null>(null);
  const [catalog, setCatalog] = useState<Catalog>(blankCatalog);
  const [message, setMessage] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const [metricId, setMetricId] = useState(""); const [metricName, setMetricName] = useState(""); const [metricAr, setMetricAr] = useState(""); const [metricExpression, setMetricExpression] = useState(""); const [metricMysqlExpression, setMetricMysqlExpression] = useState(""); const [metricAliasesEn, setMetricAliasesEn] = useState(""); const [metricAliasesAr, setMetricAliasesAr] = useState(""); const [allowed, setAllowed] = useState<string[]>([]);
  const [dimensionId, setDimensionId] = useState(""); const [dimensionName, setDimensionName] = useState(""); const [dimensionAr, setDimensionAr] = useState(""); const [dimensionExpression, setDimensionExpression] = useState(""); const [dimensionMysqlExpression, setDimensionMysqlExpression] = useState(""); const [dimensionAliasesEn, setDimensionAliasesEn] = useState(""); const [dimensionAliasesAr, setDimensionAliasesAr] = useState("");
  const [joinLeft, setJoinLeft] = useState(""); const [joinRight, setJoinRight] = useState(""); const [relationship, setRelationship] = useState("many_to_one");
  useEffect(() => { void getCatalogStatus(profileId).then((loaded) => { setStatus(loaded); const saved = localStorage.getItem(`p2i-catalog-${profileId}`); setCatalog(saved ? JSON.parse(saved) as Catalog : loaded.catalog ?? blankCatalog); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Unable to load catalog.")); }, [profileId]);
  if (!status) return <div className="card">Loading semantic catalog…</div>;
  const t = labels[locale];
  const columns = status.schema_snapshot.tables.flatMap((table) => table.columns.map((column) => ({key: [table.schema_name, table.table_name, column.name].filter(Boolean).join("."), type: column.data_type})));
  function saveDraft() { localStorage.setItem(`p2i-catalog-${profileId}`, JSON.stringify(catalog)); setMessage("Draft saved in this browser."); }
  function addMetric() { if (!metricId || !metricExpression) return setMessage("Metric ID and PostgreSQL expression are required."); setCatalog((current) => ({...current, metrics: {...current.metrics, [metricId]: {labels: {en: metricName || metricId, ar: metricAr || metricName || metricId}, aliases: {en: split(metricAliasesEn), ar: split(metricAliasesAr)}, descriptions: {en: "", ar: ""}, expressions: {postgres: metricExpression, mysql: metricMysqlExpression || metricExpression}, allowed_dimensions: allowed}}})); setMetricId(""); setMetricExpression(""); setMetricMysqlExpression(""); }
  function addDimension() { if (!dimensionId || !dimensionExpression) return setMessage("Dimension ID and PostgreSQL expression are required."); setCatalog((current) => ({...current, dimensions: {...current.dimensions, [dimensionId]: {labels: {en: dimensionName || dimensionId, ar: dimensionAr || dimensionName || dimensionId}, aliases: {en: split(dimensionAliasesEn), ar: split(dimensionAliasesAr)}, descriptions: {en: "", ar: ""}, expressions: {postgres: dimensionExpression, mysql: dimensionMysqlExpression || dimensionExpression}}}})); setDimensionId(""); setDimensionExpression(""); setDimensionMysqlExpression(""); }
  async function validate() { setPending(true); try { const result = await validateCatalog(profileId, catalog); setMessage(result.valid ? "Catalog is valid." : result.errors.join(" ")); } catch (error) { setMessage(error instanceof Error ? error.message : "Validation failed."); } finally { setPending(false); } }
  async function publish() { setPending(true); try { const result = await publishCatalog(profileId, catalog); setStatus(result); localStorage.removeItem(`p2i-catalog-${profileId}`); setMessage("Catalog published. Profile is ready."); onReady(); } catch (error) { setMessage(error instanceof Error ? error.message : "Publishing failed."); } finally { setPending(false); } }
  return <section className="stack" dir={locale === "ar" ? "rtl" : "ltr"} lang={locale}><div className="card stack"><h2>{t.title}</h2><p>Configure business terms for this schema. Database identifiers and expressions remain LTR.</p><h3>{t.schema}</h3>{status.schema_snapshot.tables.map((table) => <details key={`${table.schema_name}.${table.table_name}`}><summary dir="ltr">{[table.schema_name, table.table_name].filter(Boolean).join(".")} ({table.table_type})</summary>{table.columns.map((column) => <div className="row" dir="ltr" key={column.name}><span>{column.name} · {column.data_type}</span><select value={catalog.column_policies[[table.schema_name, table.table_name, column.name].filter(Boolean).join(".")] ?? "non_sensitive"} onChange={(event) => setCatalog((current) => ({...current, column_policies: {...current.column_policies, [[table.schema_name, table.table_name, column.name].filter(Boolean).join(".")]: event.target.value as "non_sensitive" | "sensitive" | "prohibited"}}))}><option value="non_sensitive">non_sensitive</option><option value="sensitive">sensitive</option><option value="prohibited">prohibited</option></select></div>)}</details>)}</div>
    <div className="card stack"><h3>{t.metrics}</h3><input placeholder="Metric ID (e.g. total_revenue)" value={metricId} onChange={(e) => setMetricId(e.target.value)} dir="ltr"/><input placeholder="Display name" value={metricName} onChange={(e) => setMetricName(e.target.value)}/><input placeholder="Arabic display name" value={metricAr} onChange={(e) => setMetricAr(e.target.value)}/><input placeholder="English aliases, comma separated" value={metricAliasesEn} onChange={(e) => setMetricAliasesEn(e.target.value)}/><input placeholder="Arabic aliases, comma separated" value={metricAliasesAr} onChange={(e) => setMetricAliasesAr(e.target.value)}/><input placeholder="PostgreSQL expression (e.g. SUM(orders.amount))" value={metricExpression} onChange={(e) => setMetricExpression(e.target.value)} dir="ltr"/><input placeholder="MySQL expression (optional if identical)" value={metricMysqlExpression} onChange={(e) => setMetricMysqlExpression(e.target.value)} dir="ltr"/><label>Allowed grouping dimensions</label>{Object.keys(catalog.dimensions).map((id) => <label key={id} dir="ltr"><input type="checkbox" checked={allowed.includes(id)} onChange={() => setAllowed((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id])}/>{id}</label>)}<button type="button" className="secondary" onClick={addMetric}>Add metric</button>{Object.keys(catalog.metrics).map((id) => <code key={id}>{id}</code>)}</div>
    <div className="card stack"><h3>{t.dimensions}</h3><input placeholder="Dimension ID (e.g. order_month)" value={dimensionId} onChange={(e) => setDimensionId(e.target.value)} dir="ltr"/><input placeholder="Display name" value={dimensionName} onChange={(e) => setDimensionName(e.target.value)}/><input placeholder="Arabic display name" value={dimensionAr} onChange={(e) => setDimensionAr(e.target.value)}/><input placeholder="English aliases, comma separated" value={dimensionAliasesEn} onChange={(e) => setDimensionAliasesEn(e.target.value)}/><input placeholder="Arabic aliases, comma separated" value={dimensionAliasesAr} onChange={(e) => setDimensionAliasesAr(e.target.value)}/><input placeholder="PostgreSQL expression" value={dimensionExpression} onChange={(e) => setDimensionExpression(e.target.value)} dir="ltr"/><input placeholder="MySQL expression (optional if identical)" value={dimensionMysqlExpression} onChange={(e) => setDimensionMysqlExpression(e.target.value)} dir="ltr"/><button type="button" className="secondary" onClick={addDimension}>Add dimension</button>{Object.keys(catalog.dimensions).map((id) => <code key={id}>{id}</code>)}</div>
    <div className="card stack"><h3>{t.joins}</h3><select value={joinLeft} onChange={(e) => setJoinLeft(e.target.value)}><option value="">Left key</option>{columns.map((column) => <option key={column.key} value={column.key}>{column.key}</option>)}</select><select value={joinRight} onChange={(e) => setJoinRight(e.target.value)}><option value="">Right key</option>{columns.map((column) => <option key={column.key} value={column.key}>{column.key}</option>)}</select><input value={relationship} onChange={(e) => setRelationship(e.target.value)} placeholder="Relationship"/><button type="button" className="secondary" onClick={() => joinLeft && joinRight && setCatalog((current) => ({...current, join_contracts: [...current.join_contracts, {left: joinLeft, right: joinRight, relationship, allowed_types: ["inner", "left"]}]}))}>Add join contract</button>{catalog.join_contracts.map((join) => <code key={`${join.left}-${join.right}`}>{join.left} → {join.right} ({join.relationship})</code>)}</div>
    <div className="card stack"><h3>{t.privacy}</h3><select value={catalog.privacy.privacy_unit} onChange={(e) => setCatalog((current) => ({...current, privacy: {...current.privacy, privacy_unit: e.target.value}}))}><option value="">Privacy unit</option>{columns.map((column) => <option key={column.key} value={column.key}>{column.key}</option>)}</select><input type="number" min="1" value={catalog.privacy.minimum_group_size} onChange={(e) => setCatalog((current) => ({...current, privacy: {...current.privacy, minimum_group_size: Number(e.target.value)}}))}/><div className="row"><button type="button" className="secondary" disabled={pending} onClick={saveDraft}>{t.draft}</button><button type="button" className="secondary" disabled={pending} onClick={() => void validate()}>{t.validate}</button><button type="button" disabled={pending} onClick={() => void publish()}>{t.publish}</button></div>{message ? <div role="status">{message}</div> : null}</div>
  </section>;
}
