"use client";

import {useEffect, useState} from "react";
import {Catalog, CatalogStatus, getCatalogStatus, publishCatalog, validateCatalog} from "@/lib/api";

const blankCatalog: Catalog = {catalog_version: "1", metrics: {}, dimensions: {}};
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

const labels = {
  en: {title: "Semantic Catalog", schema: "Schema browser", metrics: "Metrics", dimensions: "Dimensions", validate: "Validate", draft: "Save Draft", publish: "Publish", close: "Close"},
  ar: {title: "الكتالوج الدلالي", schema: "متصفح المخطط", metrics: "المقاييس", dimensions: "الأبعاد", validate: "تحقق", draft: "حفظ المسودة", publish: "نشر", close: "إغلاق"},
};

export function CatalogConfigurator({profileId, locale, onClose, onReady}: {profileId: string; locale: "en" | "ar"; onClose: () => void; onReady: () => void}) {
  const [status, setStatus] = useState<CatalogStatus | null>(null);
  const [catalog, setCatalog] = useState<Catalog>(blankCatalog);
  const [message, setMessage] = useState<string | null>(null);
  const [pending, setPending] = useState(false);
  const [metricId, setMetricId] = useState(""); const [metricName, setMetricName] = useState(""); const [metricAr, setMetricAr] = useState(""); const [metricExpression, setMetricExpression] = useState(""); const [metricMysqlExpression, setMetricMysqlExpression] = useState(""); const [metricAliasesEn, setMetricAliasesEn] = useState(""); const [metricAliasesAr, setMetricAliasesAr] = useState("");
  const [dimensionId, setDimensionId] = useState(""); const [dimensionName, setDimensionName] = useState(""); const [dimensionAr, setDimensionAr] = useState(""); const [dimensionExpression, setDimensionExpression] = useState(""); const [dimensionMysqlExpression, setDimensionMysqlExpression] = useState(""); const [dimensionAliasesEn, setDimensionAliasesEn] = useState(""); const [dimensionAliasesAr, setDimensionAliasesAr] = useState("");

  useEffect(() => { void getCatalogStatus(profileId).then((loaded) => { setStatus(loaded); const saved = localStorage.getItem(`p2i-catalog-${profileId}`); setCatalog(loaded.catalog ? structuredClone(loaded.catalog) : (saved ? JSON.parse(saved) as Catalog : blankCatalog)); }).catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Unable to load catalog.")); }, [profileId]);
  if (!status) return <div className="card">Loading semantic catalog…</div>;
  const t = labels[locale];
  function saveDraft() { localStorage.setItem(`p2i-catalog-${profileId}`, JSON.stringify(catalog)); setMessage("Draft saved in this browser."); }
  function addMetric() { if (!metricId || !metricExpression) return setMessage("Metric ID and PostgreSQL expression are required."); setCatalog((current) => ({...current, metrics: {...current.metrics, [metricId]: {labels: {en: metricName || metricId, ar: metricAr || metricName || metricId}, aliases: {en: split(metricAliasesEn), ar: split(metricAliasesAr)}, descriptions: {en: "", ar: ""}, expressions: {postgres: metricExpression, mysql: metricMysqlExpression || metricExpression}}}})); setMetricId(""); setMetricExpression(""); setMetricMysqlExpression(""); }
  function addDimension() { if (!dimensionId || !dimensionExpression) return setMessage("Dimension ID and PostgreSQL expression are required."); setCatalog((current) => ({...current, dimensions: {...current.dimensions, [dimensionId]: {labels: {en: dimensionName || dimensionId, ar: dimensionAr || dimensionName || dimensionId}, aliases: {en: split(dimensionAliasesEn), ar: split(dimensionAliasesAr)}, descriptions: {en: "", ar: ""}, expressions: {postgres: dimensionExpression, mysql: dimensionMysqlExpression || dimensionExpression}}}})); setDimensionId(""); setDimensionExpression(""); setDimensionMysqlExpression(""); }
  async function validate() { setPending(true); try { const result = await validateCatalog(profileId, catalog); setMessage(result.valid ? "Catalog is valid." : result.errors.join(" ")); } catch (error) { setMessage(error instanceof Error ? error.message : "Validation failed."); } finally { setPending(false); } }
  async function publish() { setPending(true); try { const result = await publishCatalog(profileId, catalog); setStatus(result); localStorage.removeItem(`p2i-catalog-${profileId}`); setMessage("Catalog published. Profile is ready."); onReady(); } catch (error) { setMessage(error instanceof Error ? error.message : "Publishing failed."); } finally { setPending(false); } }

  return <section className="stack" dir={locale === "ar" ? "rtl" : "ltr"} lang={locale}>
    <div className="card stack"><div className="row"><h2>{t.title}</h2><button type="button" className="secondary" onClick={onClose}>{t.close}</button></div><p>Configure business definitions, aliases, and preferred expressions. The schema browser shows the physical objects available to safe SQL validation.</p><h3>{t.schema}</h3>{status.schema_snapshot.tables.map((table) => <details key={`${table.schema_name}.${table.table_name}`}><summary dir="ltr">{[table.schema_name, table.table_name].filter(Boolean).join(".")} ({table.table_type})</summary>{table.columns.map((column) => <div className="row" dir="ltr" key={column.name}><span>{column.name} · {column.data_type}</span></div>)}</details>)}</div>
    <div className="card stack"><h3>{t.metrics}</h3><input placeholder="Metric ID (e.g. total_revenue)" value={metricId} onChange={(e) => setMetricId(e.target.value)} dir="ltr"/><input placeholder="Display name" value={metricName} onChange={(e) => setMetricName(e.target.value)}/><input placeholder="Arabic display name" value={metricAr} onChange={(e) => setMetricAr(e.target.value)}/><input placeholder="English aliases, comma separated" value={metricAliasesEn} onChange={(e) => setMetricAliasesEn(e.target.value)}/><input placeholder="Arabic aliases, comma separated" value={metricAliasesAr} onChange={(e) => setMetricAliasesAr(e.target.value)}/><input placeholder="Preferred PostgreSQL expression (e.g. SUM(orders.amount))" value={metricExpression} onChange={(e) => setMetricExpression(e.target.value)} dir="ltr"/><input placeholder="Preferred MySQL expression (optional if identical)" value={metricMysqlExpression} onChange={(e) => setMetricMysqlExpression(e.target.value)} dir="ltr"/><button type="button" className="secondary" onClick={addMetric}>Add metric</button>{Object.keys(catalog.metrics).map((id) => <code key={id}>{id}</code>)}</div>
    <div className="card stack"><h3>{t.dimensions}</h3><input placeholder="Dimension ID (e.g. order_month)" value={dimensionId} onChange={(e) => setDimensionId(e.target.value)} dir="ltr"/><input placeholder="Display name" value={dimensionName} onChange={(e) => setDimensionName(e.target.value)}/><input placeholder="Arabic display name" value={dimensionAr} onChange={(e) => setDimensionAr(e.target.value)}/><input placeholder="English aliases, comma separated" value={dimensionAliasesEn} onChange={(e) => setDimensionAliasesEn(e.target.value)}/><input placeholder="Arabic aliases, comma separated" value={dimensionAliasesAr} onChange={(e) => setDimensionAliasesAr(e.target.value)}/><input placeholder="Preferred PostgreSQL expression" value={dimensionExpression} onChange={(e) => setDimensionExpression(e.target.value)} dir="ltr"/><input placeholder="Preferred MySQL expression (optional if identical)" value={dimensionMysqlExpression} onChange={(e) => setDimensionMysqlExpression(e.target.value)} dir="ltr"/><button type="button" className="secondary" onClick={addDimension}>Add dimension</button>{Object.keys(catalog.dimensions).map((id) => <code key={id}>{id}</code>)}</div>
    <div className="card stack"><div className="row"><button type="button" className="secondary" disabled={pending} onClick={saveDraft}>{t.draft}</button><button type="button" className="secondary" disabled={pending} onClick={() => void validate()}>{t.validate}</button><button type="button" disabled={pending} onClick={() => void publish()}>{t.publish}</button></div>{message ? <div role="status">{message}</div> : null}</div>
  </section>;
}
